version: '3.1'
services:
  web:
    image: diegomrsantos/reservations:1.0.0-SNAPSHOT
    ports:
      - "8080:8080"
  db:
    image: postgres:10.6-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
     - "8088:8080"